// Error
export const GET_ERROR = "GET_ERROR";

// Category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_NEW_CATEGORY = "CREATE_NEW_CATEGORY";
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY";

// Brand
export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_NEW_BRAND = "CREATE_NEW_BRAND";
export const GET_SPECIFIC_BRAND = "GET_SPECIFIC_BRAND";

// Sub Category
export const CREATE_NEW_SUB_CATEGORY = "CREATE_NEW_SUB_CATEGORY";
export const GET_ALL_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";

// Products
export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
export const GET_PODUCTS_LIKE = "GET_PODUCTS_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

// Auth
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_CURERNT_USER = "GET_CURERNT_USER";
