// Error + Loading
export const GET_ERROR = "GET_ERROR";
export const SET_LOADING = "SET_LOADING";

// Category
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_NEW_CATEGORY = "CREATE_NEW_CATEGORY";
export const GET_SPECIFIC_CATEGORY = "GET_SPECIFIC_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

// Brand
export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_NEW_BRAND = "CREATE_NEW_BRAND";
export const GET_SPECIFIC_BRAND = "GET_SPECIFIC_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";

// sub-category
export const CREATE_NEW_SUB_CATEGORY = "CREATE_NEW_SUB_CATEGORY";
export const GET_ALL_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";
export const GET_SPECIFIC_SUB_CATEGORY = "GET_SPECIFIC_SUB_CATEGORY";
export const DELETED_SUB_CATEGORY = "DELETED_SUB_CATEGORY";
export const UPDATED_SUB_CATEGORY = "UPDATED_SUB_CATEGORY";

// Products
export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_BY_CATEGORY = "GET_ALL_PRODUCTS_BY_CATEGORY";
export const GET_ALL_PRODUCTS_BY_BRAND = "GET_ALL_PRODUCTS_BY_BRAND";
export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
export const GET_PODUCTS_LIKE = "GET_PODUCTS_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

// Auth
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const GET_CURERNT_USER = "GET_CURERNT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// Update User Profile & Password
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_LOADING = "UPDATE_USER_PROFILE_LOADING";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

// Review
export const CREATE_REVIEW = "CREATE_REVIEW";
export const GET_ALL_PRODUCTS_REVIEWS = "GET_ALL_PRODUCTS_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";

// WishList
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";
export const VIEW_ALL_WISHLIST = "VIEW_ALL_WISHLIST";

// Coupon
export const ADD_COUPON = "ADD_COUPON";
export const GET_ALL_COUPONS = "GET_ALL_COUPONS";
export const DELETE_COUPON = "DELETE_COUPON";
export const GET_SPECIFIC_COUPON = "GET_SPECIFIC_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";

// User Address
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
export const VIEW_ALL_USER_ADDRESSES = "VIEW_ALL_USER_ADDRESSES";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";
export const GET_SPECIFIC_USER_ADDRESS = "GET_SPECIFIC_USER_ADDRESS";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";

// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_ALL_CART_ITEMS = "GET_ALL_CART_ITEMS";
export const CLEAR_ALL_CART_ITEMS = "CLEAR_ALL_CART_ITEMS";
export const DELETE_SPECIFIC_CART_ITEM = "DELETE_SPECIFIC_CART_ITEM";
export const UPDATE_SPECIFIC_CART_ITEM = "UPDATE_SPECIFIC_CART_ITEM";
export const APPLY_COUPON = "APPLY_COUPON";

// Checkout [Cash, Card]
export const CREATE_ORDER_CASH = "CREATE_ORDER_CASH";
export const CREATE_ORDER_CARD = "CREATE_ORDER_CARD";

// Orders
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_SPECIFIC_ORDER = "GET_SPECIFIC_ORDER";
export const UPDATE_ORDER_PAY_STATUS = "UPDATE_ORDER_PAY_STATUS";
export const UPDATE_ORDER_DELIVER_STATUS = "UPDATE_ORDER_DELIVER_STATUS";

// Settings (switch Buttons)
export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";

// Rest state after specific action
export const RESET_STATE = "RESET_STATE";
export const RESET_STATE_WISHLIST = "RESET_STATE_WISHLIST";
export const RESET_STATE_REVIEW = "RESET_STATE_REVIEW";
export const RESET_STATE_CART = "RESET_STATE_CART";
export const RESET_COUPON = "RESET_COUPON";
export const RESET_CATEGORY = "RESET_CATEGORY";
